# Copyright 2026 The Sigstore Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: cut-release

on:
  push:
    tags:
      - "v*"

concurrency:
  group: "cut-release"
  cancel-in-progress: false

permissions: {}

jobs:
  release:
    permissions:
      contents: write # needed to write releases
      id-token: write # needed for keyless signing
      attestations: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Extract version of Go to use
        run: echo "GOVERSION=$(awk -F'[:@]' '/FROM golang/{print $2; exit}' Dockerfile)" >> $GITHUB_ENV

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: ${{ env.GOVERSION }}
          check-latest: true
          cache: false # avoid cache-poisoning attacks

      # Syft is used by GoReleaser to generate SBOMs
      - uses: anchore/sbom-action/download-syft@e22c389904149dbc22b58101806040fa8d37a610 # v0.24.0

      - name: Set LDFLAGS
        id: ldflags
        run: |
           LDFLAGS=$(make ldflags)
           echo "LDFLAGS=$LDFLAGS" >> $GITHUB_ENV

      - name: Run GoReleaser
        id: run-goreleaser
        uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7.2.3
        with:
          distribution: goreleaser-pro
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LDFLAGS: ${{ env.LDFLAGS }}
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
      
      - name: Generate artifact attestation
        uses: actions/attest@1e69f48acb82d1966a394da916b4c1698aa569d6 # v4.2.2
        with:
          subject-path: |
            ./dist/timestamp-server-*
            ./dist/timestamp-cli-*

  build-container:
    name: Build and push container image
    uses: ./.github/workflows/build_container.yml # zizmor: ignore[secrets-inherit]
    secrets: inherit
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
